###############################################################################
# General Configuration
###############################################################################
version: 1.1.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2017

configuration: 
 - Release
 - Debug
platform: 
  - x64
  - x86
environment:
  matrix:
  - solution_name: cpp-smallpt/cpp-smallpt.sln
  - solution_name: openmp-cpp-smallpt/cpp-smallpt.sln
  - solution_name: threads-cpp-smallpt/cpp-smallpt.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%
